### ISSUE TITLE
Error in Subtitle filter

### ISSUE THREAD

**Issue by SuNNjek** [AviSynth/AviSynthPlus#158]
Hello,

when trying to use the Subtitle filter on Linux (tested on Arch, Manjaro and WSL Debian), FFprobe (built with AviSynth enabled) crashes with the following error:
```
ffprobe: ../avs_core/core/interface.cpp:803: const AVSValue& AVSValue::OPERATOR_INDEX(int) const: Assertion `IsArray() && index>=0 && index<array_size' failed.
```

Backtrace from gdb:
```
Thread 1 "ffprobe" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffffe002535 in __GI_abort () at abort.c:79
#2  0x00007ffffe00240f in __assert_fail_base (fmt=0x7ffffe164ee0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0x7ffffdcfafb0 "IsArray() && index>=0 && index<array_size",
    file=0x7ffffdcfaef8 "../avs_core/core/interface.cpp", line=803, function=<optimized out>) at assert.c:92
#3  0x00007ffffe010102 in __GI___assert_fail (assertion=0x7ffffdcfafb0 "IsArray() && index>=0 && index<array_size",
    file=0x7ffffdcfaef8 "../avs_core/core/interface.cpp", line=803,
    function=0x7ffffdcfb240 <AVSValue::OPERATOR_INDEX(int) const::__PRETTY_FUNCTION__> "const AVSValue& AVSValue::OPERATOR_INDEX(int) const") at assert.c:101
#4  0x00007ffffd829a98 in AVSValue::OPERATOR_INDEX(int) const () from /usr/local/lib/libavisynth.so
#5  0x00007ffffd829a44 in AVSValue::operator[](int) const () from /usr/local/lib/libavisynth.so
#6  0x00007ffffdbd2eb9 in SimpleText::Create(AVSValue, void*, IScriptEnvironment*) ()
   from /usr/local/lib/libavisynth.so
#7  0x00007ffffd7c1937 in FilterConstructor::InstantiateFilter() const () from /usr/local/lib/libavisynth.so
#8  0x00007ffffd7f184c in ScriptEnvironment::Invoke(AVSValue*, char const*, AVSValue const&, char const* const*) ()
   from /usr/local/lib/libavisynth.so
#9  0x00007ffffd82ce72 in ExpFunctionCall::Evaluate(IScriptEnvironment*) () from /usr/local/lib/libavisynth.so
#10 0x00007ffffd82a0d6 in ExpExceptionTranslator::Evaluate(IScriptEnvironment*) () from /usr/local/lib/libavisynth.so
#11 0x00007ffffd82a3ee in ExpLine::Evaluate(IScriptEnvironment*) () from /usr/local/lib/libavisynth.so
#12 0x00007ffffd829f30 in ExpRootBlock::Evaluate(IScriptEnvironment*) () from /usr/local/lib/libavisynth.so
#13 0x00007ffffd82e8c5 in Eval(AVSValue, void*, IScriptEnvironment*) () from /usr/local/lib/libavisynth.so
#14 0x00007ffffd7c1937 in FilterConstructor::InstantiateFilter() const () from /usr/local/lib/libavisynth.so
#15 0x00007ffffd7f17be in ScriptEnvironment::Invoke(AVSValue*, char const*, AVSValue const&, char const* const*) ()
   from /usr/local/lib/libavisynth.so
#16 0x00007ffffd7f0bcd in ScriptEnvironment::Invoke(char const*, AVSValue, char const* const*) ()
   from /usr/local/lib/libavisynth.so
#17 0x00007ffffd82f850 in Import(AVSValue, void*, IScriptEnvironment*) () from /usr/local/lib/libavisynth.so
#18 0x00007ffffd7c1937 in FilterConstructor::InstantiateFilter() const () from /usr/local/lib/libavisynth.so
#19 0x00007ffffd7f17be in ScriptEnvironment::Invoke(AVSValue*, char const*, AVSValue const&, char const* const*) ()
--Type <RET> for more, q to quit, c to continue without paging--
   /usr/local/lib/libavisynth.so
#20 0x00007ffffd7f0bcd in ScriptEnvironment::Invoke(char const*, AVSValue, char const* const*) ()
   from /usr/local/lib/libavisynth.so
#21 0x00007ffffd8054ee in avs_invoke () from /usr/local/lib/libavisynth.so
#22 0x0000000008112e5b in ?? ()
#23 0x00000000084c35da in ?? ()
#24 0x0000000008181988 in ?? ()
#25 0x00007ffffe00409b in __libc_start_main (main=0x81812f0, argc=3, argv=0x7ffffffedb78, init=<optimized out>,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffffffedb68) at ../csu/libc-start.c:308
#26 0x000000000818359a in ?? ()
```

**Comment by pinterf** [comment]
Thanks for the report, temporarily I made SubTitle as an alias for Text, still, But I gave Text an additional "bold" parameter which is not supplied when bypassing SubTitle parameters to Text. Workaround: use "Text" instead of "SubTitle" until the fix.
