### ISSUE TITLE
access violation bug in  Avisynth+ 32bit

### ISSUE THREAD

**Issue by fuchanghao** [AviSynth/AviSynthPlus#77]
r2043-MT-test download From.

http://avs-plus.net/builds

Worked Fine with 64bit with avspmod.

But Crashed with 32bit AVSpmod or reading avs in megui etc.

[Wed Jul 13 23:02:33 2016]
Traceback (most recent call last):
  File "run.py", line 49, in <module>
  File "avsp.pyo", line 18881, in main
  File "wx\_core.pyo", line 7981, in __init__
  File "wx\_core.pyo", line 7555, in _BootstrapApp
  File "avsp.pyo", line 18868, in OnInit
  File "avsp.pyo", line 5229, in __init__
  File "avsp.pyo", line 6290, in defineFilterInfo
  File "avsp.pyo", line 6617, in getFilterInfoFromAvisynth
  File "avisynth.pyo", line 242, in invoke
WindowsError: exception: access violation reading 0x00000001

**Comment by pylorak** [comment]
Please provide script that can be used to reproduce the bug.

**Comment by fuchanghao** [comment]
update to r2062 with nnedi3 v0.9.4.23。

bug fixed.

Seems that's a nnedi3 bug.
